import { NAME } from './constants';

const FETCH_PROJECT = `${ NAME }/FETCH_PROJECT`;
const SET_CURRENT_TILE = `${ NAME }/SET_CURRENT_TILE`;
const SET_LAYERS = `${ NAME }/SET_LAYERS`;
const SET_LAYER_THUMB = `${ NAME }/SET_LAYER_THUMB`;
const SET_PROJECT = `${ NAME }/SET_PROJECT`;
const SET_PROJECTS = `${ NAME }/SET_PROJECTS`;
const SET_TILES = `${ NAME }/SET_TILES`;
const SET_TILES_CACHE = `${ NAME }/SET_TILES_CACHE`;

export {
  FETCH_PROJECT,
  SET_CURRENT_TILE,
  SET_LAYERS,
  SET_LAYER_THUMB,
  SET_PROJECT,
  SET_PROJECTS,
  SET_TILES,
  SET_TILES_CACHE,
};
