import { NAME } from './constants';

const CLEAR_DIALOG_ERROR = `${ NAME }/CLEAR_DIALOG_ERROR`;
const SET_DIALOG_ERROR = `${ NAME }/SET_DIALOG_ERROR`;
const SET_PREVIOUS_VIEW = `${ NAME }/SET_PREVIOUS_VIEW`;
const SET_PROJECT = `${ NAME }/SET_PROJECT`;
const SET_PROJECTS = `${ NAME }/SET_PROJECTS`;
const SET_SHELL_CLASS = `${ NAME }/SET_SHELL_CLASS`;
const SET_SCROLL_POS = `${ NAME }/SET_SCROLL_POS`;
const SET_VIEW_DATA = `${ NAME }/SET_VIEW_DATA`;

export {
  CLEAR_DIALOG_ERROR,
  SET_DIALOG_ERROR,
  SET_PREVIOUS_VIEW,
  SET_PROJECT,
  SET_PROJECTS,
  SET_SHELL_CLASS,
  SET_SCROLL_POS,
  SET_VIEW_DATA,
};
